version: "3.9"

networks:
  yape_challenge:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - yape_challenge

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    networks:
      - yape_challenge

  yape-transaction:
    build:
      context: .
      dockerfile: Dockerfile.transaction
    container_name: yape-transaction
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_yape:5432/dbtransactionv1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres_yape
    networks:
      - yape_challenge

  yape-antifraud:
    build:
      context: .
      dockerfile: Dockerfile.antifraud
    container_name: yape-antifraud
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    networks:
      - yape_challenge

  postgres_yape:
    image: postgres:14
    container_name: postgres_yape
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbtransactionv1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yape_challenge
